---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-driftwatch-io-v1alpha1-driftcheck
  failurePolicy: Fail
  name: mdriftcheck.kb.io
  rules:
  - apiGroups:
    - driftwatch.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - driftchecks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-driftwatch-io-v1alpha1-driftcheck
  failurePolicy: Fail
  name: vdriftcheck.kb.io
  rules:
  - apiGroups:
    - driftwatch.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - driftchecks
  sideEffects: None
