#!/usr/bin/env bash
# Renders config/prometheus/rules.yaml as a plain Prometheus rule file.
#
# The committed file is a PrometheusRule custom resource, which is what the
# operator consumes. Prometheus itself parses rule files strictly and rejects
# the Kubernetes wrapper — `field apiVersion not found in type
# rulefmt.RuleGroups` — so the demo, which runs Prometheus directly, needs the
# `spec` on its own.
#
# Generated rather than committed a second time. Two copies of ten alerts is two
# things to keep in step, and the one that would fall behind is the demo — so
# the project would end up showing alerts the cluster no longer has, which is
# worse than showing none.
set -euo pipefail

cd "$(dirname "$0")/.."

SRC=config/prometheus/rules.yaml
DST="${1:-deploy/demo/rules.generated.yaml}"

if [ ! -f "$SRC" ]; then
  echo "prom-rules: $SRC does not exist" >&2
  exit 1
fi

{
  echo "# Generated by hack/prom-rules.sh from config/prometheus/rules.yaml."
  echo "# Do not edit: the source of truth is the PrometheusRule that ships to"
  echo "# the cluster, so that the demo and the deployment alert on the same"
  echo "# expressions."
  echo ""

  # Everything from `groups:` to the end, de-indented by two so that what was
  # nested under `spec:` becomes top level.
  sed -n '/^  groups:/,$p' "$SRC" | sed 's/^  //'
} >"$DST"

if ! grep -q '^groups:' "$DST"; then
  echo "prom-rules: $DST has no top-level groups: key" >&2
  echo "The layout of $SRC changed; this script assumes spec.groups at indent 2." >&2
  exit 1
fi

echo "prom-rules: wrote $DST ($(grep -c 'alert:' "$DST") alerts)"
