#!/usr/bin/env bash
# Renders config/crd/bases/*.yaml into the Helm chart as a template.
#
# Two things make this a script rather than a copy.
#
# The CRD is templated rather than dropped in the chart's crds/ directory. Helm
# installs crds/ once and never upgrades it, so for an API still at v1alpha1
# every schema change would need a manual `kubectl apply` that nothing reminds
# you about. Templating it means `helm upgrade` moves the schema with the chart,
# at the cost of `helm uninstall` being able to remove it — which is what the
# resource-policy annotation this script inserts prevents.
#
# And the CRD's own defaults contain Go template syntax: keyTemplate defaults to
# "{{.Key}}". Helm would evaluate that at install time against a context with no
# .Key and render an empty string, so every DriftCheck created without an
# explicit keyTemplate would silently get an empty key template. Every brace
# pair is escaped here so Helm emits it literally.
#
# Usage:
#   hack/sync-helm-crd.sh            # check, exit 1 on drift
#   hack/sync-helm-crd.sh --write    # regenerate
set -euo pipefail

cd "$(dirname "$0")/.."

SRC=config/crd/bases/driftwatch.io_driftchecks.yaml
DST=deploy/helm/driftwatch/templates/crd-driftchecks.yaml

render() {
  cat <<'HEADER'
{{- if .Values.crds.install }}
{{/*
Generated by hack/sync-helm-crd.sh from
config/crd/bases/driftwatch.io_driftchecks.yaml. Do not edit by hand — CI runs
that script in check mode and fails if this file and the generated CRD disagree.

Every {{ "{{" }} below is an escaped brace pair, not a Helm action: the CRD's
own schema defaults contain Go template syntax (keyTemplate defaults to
{{ "{{" }}.Key}}), and Helm would otherwise evaluate them at install time
against a context that has no .Key.
*/}}
HEADER

  # Escape Go template openers, then insert the resource policy under the
  # existing metadata.annotations block. awk rather than sed for the insert,
  # because it needs to fire on the first annotations key at metadata depth and
  # nowhere else — the schema has properties called "annotations" further down.
  sed 's/{{/{{ "{{" }}/g' "$SRC" | awk '
    /^  annotations:$/ && !done {
      print
      print "{{- if .Values.crds.keepOnUninstall }}"
      print "    \"helm.sh/resource-policy\": keep"
      print "{{- end }}"
      done = 1
      next
    }
    { print }
  '

  echo '{{- end }}'
}

if [ ! -f "$SRC" ]; then
  echo "sync-helm-crd: $SRC does not exist; run 'make manifests' first" >&2
  exit 1
fi

if [ "${1:-}" = "--write" ]; then
  render >"$DST"
  echo "sync-helm-crd: wrote $DST"
  exit 0
fi

GENERATED=$(mktemp)
trap 'rm -f "$GENERATED"' EXIT
render >"$GENERATED"

if [ ! -f "$DST" ]; then
  echo "sync-helm-crd: $DST does not exist" >&2
  echo "run: hack/sync-helm-crd.sh --write" >&2
  exit 1
fi

# CRLF stripped, so a checkout on Windows does not fail for a reason that has
# nothing to do with the schema.
if diff -u <(tr -d '\r' <"$DST") <(tr -d '\r' <"$GENERATED"); then
  echo "sync-helm-crd: ok"
  exit 0
fi

echo "" >&2
echo "sync-helm-crd: $DST is out of date with $SRC" >&2
echo "run: hack/sync-helm-crd.sh --write" >&2
exit 1
